version: '3.8'

services:
  wordpress:
    image: wordpress:6.4-php8.2-apache
    container_name: wordpress-multisite
    restart: unless-stopped
    depends_on:
      - wordpress-db
      - wordpress-redis
    environment:
      - WORDPRESS_DB_HOST=wordpress-db:3306
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-wp_secure_pass_518f579bc2f50d8d}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_CONFIG_EXTRA=define("WP_HOME", "http://157.230.13.13:8080"); define("WP_SITEURL", "http://157.230.13.13:8080"); define("WP_REDIS_HOST", "wordpress-redis"); define("WP_REDIS_PORT", 6379);
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8080:80"
    networks:
      - wordpress_network

  wordpress-db:
    image: mysql:8.0
    container_name: wordpress-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_secure_password}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME:-wordpress}
      - MYSQL_USER=${WORDPRESS_DB_USER:-wordpress}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD:-wp_secure_pass_518f579bc2f50d8d}
    volumes:
      - wordpress_db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - wordpress_network
    command: --default-authentication-plugin=mysql_native_password

  wordpress-redis:
    image: redis:7-alpine
    container_name: wordpress-redis
    restart: unless-stopped
    volumes:
      - wordpress_redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - wordpress_network
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wordpress-phpmyadmin
    restart: unless-stopped
    depends_on:
      - wordpress-db
    environment:
      - PMA_HOST=wordpress-db
      - PMA_PORT=3306
      - PMA_USER=${WORDPRESS_DB_USER:-wordpress}
      - PMA_PASSWORD=${WORDPRESS_DB_PASSWORD:-wp_secure_pass_518f579bc2f50d8d}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_secure_password}
    ports:
      - "8081:80"
    networks:
      - wordpress_network

volumes:
  wordpress_data:
    driver: local
  wordpress_db_data:
    driver: local
  wordpress_redis_data:
    driver: local

networks:
  wordpress_network:
    driver: bridge 